################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
C++_DEPS := 
OBJS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
tools/testCreate/TemplateFiles \
omacTest/Src/Native \
omacTest/Src/Native/GNU_S \
csmaMACTest/Src/Native \
csmaMACTest/Src/Native/GNU_S \
USB/Src/Native \
USB/Src/Native/GNU_S \
USARTTest/Src/Native/Level_0D \
USARTTest/Src/Native/Level_0D/GNU_S \
USARTTest/Src/Native/Level_0C \
USARTTest/Src/Native/Level_0C/GNU_S \
USARTTest/Src/Native/Level_0B \
USARTTest/Src/Native/Level_0B/GNU_S \
USARTTest/Src/Native/Level_0A \
USARTTest/Src/Native/Level_0A/GNU_S \
Timer/Src/Native/RollOverBug \
Timer/Src/Native/RollOverBug/GNU_S \
Timer/Src/Native/Basic \
Timer/Src/Native/Basic/GNU_S \
SPI/Src/Native \
SPI/Src/Native/GNU_S \
SDIO/Src/Native \
SDIO/Src/Native/Level_1 \
SDIO/Src/Native/Level_1/GNU_S \
SDIO/Src/Native/GNU_S \
Radio/Src/Native/ChangeTxPower/Master/Level_1A \
Radio/Src/Native/ChangeTxPower/Master/Level_1A/GNU_S \
Radio/Src/Native/ChangeTxPower/Master/Level_0A \
Radio/Src/Native/ChangeTxPower/Master/Level_0A/GNU_S \
Radio/Src/Native/ChangeChannel/Slave \
Radio/Src/Native/ChangeChannel/Slave/GNU_S \
Radio/Src/Native/ChangeChannel/Master/Level_1A \
Radio/Src/Native/ChangeChannel/Master/Level_1A/GNU_S \
Radio/Src/Native/ChangeChannel/Master/Level_0B \
Radio/Src/Native/ChangeChannel/Master/Level_0B/GNU_S \
Radio/Src/Native/ChangeChannel/Master/Level_0A \
Radio/Src/Native/ChangeChannel/Master/Level_0A/GNU_S \
Radio/Src/Native/Basic/Slave \
Radio/Src/Native/Basic/Slave/GNU_S \
Radio/Src/Native/Basic/Master/Sleep_Level_1C \
Radio/Src/Native/Basic/Master/Sleep_Level_1C/GNU_S \
Radio/Src/Native/Basic/Master/Sleep_Level_1B \
Radio/Src/Native/Basic/Master/Sleep_Level_1B/GNU_S \
Radio/Src/Native/Basic/Master/Sleep_Level_1A \
Radio/Src/Native/Basic/Master/Sleep_Level_1A/GNU_S \
Radio/Src/Native/Basic/Master/Sleep_Level_0A \
Radio/Src/Native/Basic/Master/Sleep_Level_0A/GNU_S \
Radio/Src/Native/Basic/Master/Level_0B \
Radio/Src/Native/Basic/Master/Level_0B/GNU_S \
Radio/Src/Native/Basic/Master/Level_0A \
Radio/Src/Native/Basic/Master/Level_0A/GNU_S \
RTC/Src/Native \
RTC/Src/Native/GNU_S \
Power/Src/Native \
Power/Src/Native/GNU_S \
NOR/Src/Native/Level_1 \
NOR/Src/Native/Level_1/GNU_S \
NOR/Src/Native/Level_0C \
NOR/Src/Native/Level_0C/GNU_S \
NOR/Src/Native/Level_0B \
NOR/Src/Native/Level_0B/GNU_S \
NOR/Src/Native/Level_0A \
NOR/Src/Native/Level_0A/GNU_S \
INTC/Src/Native \
INTC/Src/Native/GNU_S \
HALTimerTest/Src/Native \
HALTimerTest/Src/Native/GNU_S \
GlobalLock/Src/Native/Level_0B \
GlobalLock/Src/Native/Level_0B/GNU_S \
GlobalLock/Src/Native/Level_0A \
GlobalLock/Src/Native/Level_0A/GNU_S \
GPIO/Src/Native \
GPIO/Src/Native/GNU_S \
DataStore/Src/Native \
DataStore/Src/Native/GNU_S \
DAC/Src/Native \
DAC/Src/Native/GNU_S \
Clock/Src/Native \
Clock/Src/Native/GNU_S \
BlockStorageTest/Src/Native \
BlockStorageTest/Src/Native/GNU_S \
ADC/Src/Native \
ADC/Src/Native/GNU_S \

